DROP TABLE NODE IF EXISTS;

DROP SEQUENCE IF EXISTS NODE_SEQUENCE;

CREATE TABLE NODE (
   NODE_ID BIGINT NOT NULL,
	NODE_NAME VARCHAR(255) NOT NULL,
	PARENT_NODE_ID BIGINT,
	ROOT_NODE_ID BIGINT,
	NODE_CHILDREN BIGINT,
	PRIMARY KEY (NODE_ID)
);

create sequence NODE_SEQUENCE start with 1 increment by 1;
   
ALTER TABLE NODE ADD CONSTRAINT FK_PARENT_NODE FOREIGN KEY (PARENT_NODE_ID) REFERENCES NODE;
ALTER TABLE NODE ADD CONSTRAINT FK_ROOT_NODE FOREIGN KEY (ROOT_NODE_ID) REFERENCES NODE;
ALTER TABLE NODE ADD CONSTRAINT FK_CHILDREN_NODE FOREIGN KEY (NODE_CHILDREN) REFERENCES NODE;

insert into node(NODE_ID,NODE_NAME,PARENT_NODE_ID,ROOT_NODE_ID,NODE_CHILDREN) values (NODE_SEQUENCE.nextval,'Root',null,null,null);